#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

export NODE_ENV=production

echo "Building browser version"
../node_modules/.bin/webpack --colors --progress --config webpack.js --env production --display-error-details